/**
 * WYN Schema Comparator Engine - Inspector Data Reader
 * Reads JSON artifacts generated by the Database Inspector from reports/db-inspector/.
 */

import fs from 'fs';
import path from 'path';
import {
  InspectorTableRecord,
  InspectorColumnRecord,
  InspectorPKRecord,
  InspectorFKRecord,
  InspectorConstraintRecord,
  InspectorIndexRecord,
} from '../types';

export interface InspectorData {
  tables: InspectorTableRecord[];
  columns: InspectorColumnRecord[];
  primaryKeys: InspectorPKRecord[];
  foreignKeys: InspectorFKRecord[];
  constraints: InspectorConstraintRecord[];
  indexes: InspectorIndexRecord[];
}

export class InspectorDataReader {
  public readInspectorReports(inspectorDir: string): InspectorData {
    return {
      tables: this.readJsonRecords<InspectorTableRecord>(inspectorDir, 'tables.json'),
      columns: this.readJsonRecords<InspectorColumnRecord>(inspectorDir, 'columns.json'),
      primaryKeys: this.readJsonRecords<InspectorPKRecord>(inspectorDir, 'primary_keys.json'),
      foreignKeys: this.readJsonRecords<InspectorFKRecord>(inspectorDir, 'foreign_keys.json'),
      constraints: this.readJsonRecords<InspectorConstraintRecord>(inspectorDir, 'constraints.json'),
      indexes: this.readJsonRecords<InspectorIndexRecord>(inspectorDir, 'indexes.json'),
    };
  }

  private readJsonRecords<T>(dir: string, filename: string): T[] {
    const filePath = path.join(dir, filename);
    if (!fs.existsSync(filePath)) {
      return [];
    }
    try {
      const content = fs.readFileSync(filePath, 'utf-8');
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed)) return parsed as T[];
      if (parsed && Array.isArray(parsed.records)) return parsed.records as T[];
      return [];
    } catch {
      return [];
    }
  }
}
